require('dotenv').config({ silent: true });

var mongoose = require('mongoose');
mongoose.connect(process.env.PROJONE_DB_CONN);

var Animal = require('./models/animal');

var animalData = [
  {
    name: 'Rosco',
    species: 'Dog',
    breed: 'German Shepherd',
    size: 'Large',
    age: 7,
    gender: 'Female',
    hairType: 'Medium',
    family: 'Dogs',
    energyLevel: 'Medium',
    trainingNeeds: 'House Trained',
    dependency: 'Left alone for short period of time',
    hypoallergenic: 'No',
    imageUrl: 'http://r.ddmcdn.com/s_f/o_1/APL/uploads/2014/04/1394746213009gshep.jpg" alt="german shepherd',
    shelter: '58eab6c7b057f6b916f710bf'
  },
  {
    name: 'Star',
    species: 'Dog',
    breed: 'Golden Retriever',
    size: 'Medium',
    age: 1,
    gender: 'Male',
    hairType: 'Medium',
    family: 'All',
    energyLevel: 'Medium',
    trainingNeeds: 'House trained',
    dependency: 'Left alone for short period of time',
    hypoallergenic: 'No',
    imageUrl: 'http://www.dogbreedslist.info/uploads/allimg/dog-pictures/Golden-Retriever-2.jpg" alt="golden retriever',
    shelter: '58eab6c7b057f6b916f710bf'
  },
    {
      name:'Danny',
      species:'Dog',
      breed:'Labroador Retriever',
      size:'Large',
      age: 3,
      gender:'Male',
      hairType:'Short',
      family:'All',
      energyLevel:'High',
      trainingNeeds:'House Trained',
      dependency:'Needs supervision',
      hypoallergenic:'No',
      imageUrl:'http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_22988_labrador-retriever.jpg',
      shelter:'58eab6c7b057f6b916f710c1'
    },
    {
      name:'Bobby',
      species:'Dog',
      breed:'Bulldog',
      size: 'Small',
      age: 5,
      gender: 'Male',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'Low',
      trainingNeeds: 'House trained',
      dependency: 'Left alone for short period of time',
      hypoallergenic: 'No',
      imageUrl: 'http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23140_bulldog-460x290.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name:'Fritz',
      species:'Dog',
      breed:'Beagle',
      size: 'Medium',
      age: 3,
      gender: 'Male',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'Trainable',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23012_beagle.jpg',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name:'Cindy',
      species:'Dog',
      breed:'French Bulldog',
      size: 'Small',
      age: 4,
      gender: 'Female',
      hairType: 'Short',
      family: 'Dogs',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://images1.villagevoice.com/imager/u/745xauto/8001321/shutterstock_113945161.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name:'Casandra',
      species:'Dog',
      breed:'Poodle',
      size: 'Medium',
      age: 10,
      gender: 'Female',
      hairType: 'Medium',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'Needs Training',
      dependency: 'Needs Supervision',
      hypoallergenic: 'Yes',
      imageUrl: 'http://animalia-life.club/data_images/poodle/poodle6.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name:'Duke',
      species:'Dog',
      breed:'Rottweiler',
      size: 'Large',
      age: 7,
      gender: 'Male',
      hairType: 'Short',
      family: 'Dogs',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://www.dogbreedinfo.com/images12/Rottweilerbear1year.JPG',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name:'Apple',
      species:'Dog',
      breed:'Yorkshire Terrier',
      size: 'Small',
      age: 3,
      gender: 'Female',
      hairType: 'Long',
      family: 'Dogs',
      energyLevel: 'Medium',
      trainingNeeds: 'Needs Training',
      dependency: 'Left alone for short period of time',
      hypoallergenic: 'No',
      imageUrl: 'http://r.ddmcdn.com/s_f/o_1/APL/uploads/2014/04/1394745477759yorkie.jpg',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name:'Max',
      species:'Dog',
      breed:'Boxer',
      size: 'Medium',
      age: 7,
      gender: 'Male',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'High',
      trainingNeeds: 'Trainable',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_22916_boxer-460x290.jpg',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name:'Lady',
      species:'Dog',
      breed:'German Shorthaired Pointer',
      size: 'Medium',
      age: 1,
      gender: 'Female',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'High',
      trainingNeeds: 'House Trained',
      dependency: 'Left alone for short periods of time',
      hypoallergenic: 'No',
      imageUrl: 'http://www.dogbreedinfo.com/images10/GermanShorthairedPointerP4130205.jpg',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name:'Elsa',
      species:'Dog',
      breed:'Siberian Husky',
      size: 'Medium',
      age: 3,
      gender: 'Female',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'High',
      trainingNeeds: 'Needs Training',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name:'Shorty',
      species:'Dog',
      breed:'Dachshund',
      size: 'Small',
      age: 5,
      gender: 'Male',
      hairType: 'Medium',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://www.petimagery.com/wp-content/uploads/2011/10/minature-daschund_A103943.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name:'Georgia',
      species:'Dog',
      breed:'Great Dane',
      size: 'Large',
      age: 3,
      gender: 'Female',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'Needs Training',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://www.danescountry.com/images/Sophie_7mths.JPG',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name:'Doby',
      species:'Dog',
      breed:'Doberman Pinscher',
      size: 'Large',
      age: 5,
      gender: 'Male',
      hairType: 'Short',
      family: '',
      energyLevel: 'High',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'https://assets.vetary.com/media/seo_content/dog/doberman-pinscher-med.jpg',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name:'Milton',
      species:'Dog',
      breed:'Australian Shepherd',
      size: 'Medium',
      age: 4,
      gender: 'Male',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'High',
      trainingNeeds: 'House Trained',
      dependency: 'Left alone for short periods of time',
      hypoallergenic: 'No',
      imageUrl: 'http://www.itsdogbreeds.info/images/australian-shepherd-photo.jpg',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name: 'Billie',
      species: 'Dog',
      breed: 'Miniature Schnauzer',
      size: 'Small',
      age: 7,
      gender: 'Female',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Miniature_Schnauzer_02.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name: 'Tiara',
      species: 'Dog',
      breed: 'Pembroke Welsh Corgi',
      size: 'Medium',
      age: 6,
      gender: 'Female',
      hairType: 'Short',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'Trainable',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://www.dogbreedinfo.com/images10/PembrokeLucy2.jpg',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name: 'Charlie',
      species: 'Dog',
      breed: 'Cavalier King Charles Spaniel',
      size: 'Small',
      age: 4,
      gender: 'Male',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'Needs Training',
      dependency: 'Left alone for short periods of time',
      hypoallergenic: 'No',
      imageUrl: 'http://www.yourpurebredpuppy.com/dogbreeds/photos-CD/cavalierkingcharlesspanielsf6.jpg',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name: 'Parker',
      species: 'Dog',
      breed: 'Shih Tzu',
      size: 'Small',
      age: 6,
      gender: 'Male',
      hairType: 'Long',
      family: 'Dogs',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://d3cg3jn1dlk00f.cloudfront.net/6/5/1/11.png',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name: 'Barry',
      species: 'Dog',
      breed: 'Boston Terrier',
      size: 'Small',
      age: 5,
      gender: 'Male',
      hairType: 'Short',
      family: 'Cats',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23138_boston-terrier-460x290.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name: 'Tinkerbell',
      species: 'Dog',
      breed: 'Pomeranian',
      size: 'Small',
      age: 2,
      gender: 'Female',
      hairType: 'Long',
      family: 'Dogs',
      energyLevel: 'Medium',
      trainingNeeds: 'Needs Training',
      dependency: 'Left alone for short periods of time',
      hypoallergenic: 'No',
      imageUrl: 'http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23122_pomeranian.jpg',
      shelter: '58eab6c7b057f6b916f710bf'
    },
    {
      name: 'Pebbles',
      species: 'Dog',
      breed: 'Havanese',
      size: 'Small',
      age: 5,
      gender: 'Female',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Independent',
      hypoallergenic: 'No',
      imageUrl: 'http://www.allsmalldogbreeds.com/breeds/havanese.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    },
    {
      name: 'Candice',
      species: 'Dog',
      breed: 'Shetland Sheepdog',
      size: 'Medium',
      age: 1,
      gender: 'Female',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'Medium',
      trainingNeeds: 'House Trained',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://pbs.twimg.com/media/CVbNy-1UwAAh1DX.jpg:large',
      shelter: '58eab6c7b057f6b916f710c1'
    },
    {
      name: 'Chance',
      species: 'Dog',
      breed: 'Brittany Spaniel',
      size: 'Medium',
      age: 4,
      gender: 'Male',
      hairType: 'Long',
      family: 'All',
      energyLevel: 'High',
      trainingNeeds: 'Needs Training',
      dependency: 'Needs Supervision',
      hypoallergenic: 'No',
      imageUrl: 'http://www.sportingdogsaz.com/sdaz/images/breeds/BrittanySpaniel/Brittany%20Spaniel.jpg',
      shelter: '58eab6c7b057f6b916f710c0'
    }
];

Animal.remove({}, function(err, removed) {
  if (err) {
    console.log('Database Error: ', err);
  }

  Animal.create(animalData, function(err, animals) {
    if (err) {
      console.log('Database Error: ', err);
    }

    console.log('Animals inserted: ', animals);
    process.exit();
  });
});
